import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next AppCreate Next AppCreate Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Create Next AppCreate Next AppCreate Next AppCreate Next AppCreate
          Next AppCreate Next AppCreate Next AppCreate Next AppCreate Next
          AppCreate Next AppCreate Next AppCreate Next AppCreate Next AppCreate
          Next AppCreate Next AppCreate Next AppCreate Next AppCreate Next
          AppCreate Next AppCreate Next AppCreate Next AppCreate Next AppCreate
          Next AppCreate Next AppCreate Next AppCreate Next App
        </h1>
      </main>
    </div>
  );
}
